version: '3.8'

services: 
  db:
    image: mysql
    container_name: mysql
    volumes:
        - ./mysql/data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_DATABASE=wallet_stack_test
        - MYSQL_ROOT_PASSWORD=1234
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQLDB_USER=$MYSQLDB_USER
      - MYSQLDB_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQLDB_DATABASE=$MYSQLDB_DATABASE
      - MYSQLDB_DOCKER_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true