version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=disease
      - MYSQL_ROOT_PASSWORD=1234
  web:
    build: .
    environment:
      MYSQLDB_DATABASE: disease
      MYSQLDB_USER: root
      MYSQLDB_ROOT_PASSWORD: 1234
      MYSQLDB_HOST: db
    ports:
      - "5000:5000"
    depends_on:
      - db